name: Python App Devops Workflow

on:
    push:
        branches: [ main ]
    pull_request:
        branches: [ main ]

jobs:
    build:
        runs-on: ubuntu-latest
        environment: production
        steps:
        - uses: actions/checkout@v3

        - name: Set Up Python
          uses: actions/setup-python@v4
          with:
            python-version: '3.12'
        
        - name: Install Dependencies
          run: |
            python -m pip install --upgrade pip
            pip install pytest
            pip install -r requirements.txt
        
        - name: Run Pytest
          run: pytest
        
        - name: Get Docker Login
          if: success() # step only runs if test pass
          uses: docker/login-action@v2
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}
        
        - name: Build and Push to Docker Image
          if: success() # step only runs if test pass
          uses: docker/build-push-action@v3
          with:
            push: true
            tags: vinacpu/devops-app:latest
            